### ISSUE TITLE
I can't see some of the basic prime numbers

### ISSUE THREAD

**Issue by HilitOreny** [craigmayhew/bigprimes.net#108]
Dear Craig Mayhew,

I was looking for a list of the first 10 prime numbers (2, 3, 5, 7, 11, 13, etc.), and stumbled upon your website:

https://www.bigprimes.net/archive/prime

Surprisingly, instead of a list, I saw this:

![image](https://user-images.githubusercontent.com/69712717/99026664-290bb800-2574-11eb-9375-60cf05f415ac.png)

Where's 3, 5, 7, etc.?

Have I missed something, or is it a bug?

Thanks for taking the time to read this,  Keep me informed . . .

Hilit Oreny

**Comment by craigmayhew** [comment]
That is certainly a bug! Thanks for reporting. I'll take a look when I can and update this ticket when fixed!

**Comment by craigmayhew** [comment]
Thanks once again. This bug has now been fixed.
