### ISSUE TITLE
Torrent error

### ISSUE THREAD

**Issue by ErikHendriks** [craigmayhew/bigprimes.net#15]

**Comment by craigmayhew** [comment]
Hi Erik, thanks for reporting the bug. I will generate a new archive and correct this when I can.

The reason for the error is that unfortunately the 7z file has been lost from the S3 bucket and no one is still seeding the file. I suspect this was human error at some point in the past.

**Comment by ErikHendriks** [comment]
Thank you Craig, i got the file.
