### ISSUE TITLE
A query

### ISSUE THREAD

**Issue by Jaimalo** [craigmayhew/bigprimes.net#17]
sorry for the inconvenience ... come to this page because a few years ago download a torrent file with 1400 million prime numbers and it was necessary to buy a program called EmEditor to open it .. download and buy made from my cell phone ... after I passed them to my Laptop and mounted the software and I was able to open the file successfully ... I have several discoveries in the field of Prime Numbers ... such as Gaps and everything related to arithmetic progressions of primes and what is related to the hypothesis of Riemman and the distribution of the cousins ​​... at the moment I write a book to publicize the achievements ... it turns out that I want to thank the person who put on the Web the file of the 1400 million cousins ​​and I could not go back to find it in google ... in that then I communicated with him in Brazil via e-mail, he answered me in Portuguese but I also do not find that email ... I want to know if you know anything about it because just us you tell about 1400 million prime numbers on your page ... again excuse me but it is important for me to give you the recognition ... without this file I did not open what I have achieved ... thank you for your attention ... please reply if possible to my e-mail address

**Comment by Jaimalo** [comment]
sorry for the inconvenience ... come to this page because a few years ago download a torrent file with 1400 million prime numbers and it was necessary to buy a program called EmEditor to open it .. download and buy made from my cell phone ... after I passed them to my Laptop and mounted the software and I was able to open the file successfully ... I have several discoveries in the field of Prime Numbers ... such as Gaps and everything related to arithmetic progressions of primes and what is related to the hypothesis of Riemman and the distribution of the cousins ​​... at the moment I write a book to publicize the achievements ... it turns out that I want to thank the person who put on the Web the file of the 1400 million cousins ​​and I could not go back to find it in google ... in that then I communicated with him in Brazil via e-mail, he answered me in Portuguese but I also do not find that email ... I want to know if you know anything about it because just us you tell about 1400 million prime numbers on your page ... again excuse me but it is important for me to give you the recognition ... without this file I did not open what I have achieved ... thank you for your attention ... please reply if possible to my e-mail address jmaldonadol50@yahoo.com

**Comment by craigmayhew** [comment]
Hi Jaimalo,

I've responded via email and removed your email address from the public comments to protect your privacy.

Have a great day!

Kind regards,
Craig Mayhee

**Comment by Jaimalo** [comment]
Gracias Craig ...
