### ISSUE TITLE
Find nth prime number does not work correctly

### ISSUE THREAD

**Issue by Nordicus** [craigmayhew/bigprimes.net#2]
I was looking for what percentage of unix time was prime, and so trying to find the number of primes that can be represented as a unix time stamp. For this, I needed to use the nth prime feature and got the following.
![image](https://cloud.githubusercontent.com/assets/3797466/25095581/38d181b0-2394-11e7-9094-046f674b9fba.png)

**Comment by craigmayhew** [comment]
Thank you, I will fix this.

In the mean time, the page I think you want is this one: http://www.bigprimes.net/archive/prime/1050976/
