### ISSUE TITLE
Cruncher max digits is 43

### ISSUE THREAD

**Issue by flansel** [craigmayhew/bigprimes.net#26]
Big_primes.js seems to be obfuscated so I cant debug easily, but it is a index out of bound exception.

Ex: https://www.bigprimes.net/cruncher/999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999/

**Comment by craigmayhew** [comment]
Thanks @flansel for the bug report! I wasn't able to replicate this! What occurs and what steps lead to this problem?

**Comment by flansel** [comment]
If you click the link provided you should see that it redirects to the main page rather than the Cruncher output page

**Comment by craigmayhew** [comment]
Thank you for the bug report! PR #42 solves this.
