### ISSUE TITLE
2 is the first prime and 3 the second.

### ISSUE THREAD

**Issue by zaxonus** [craigmayhew/bigprimes.net#6]
Hello,

My name is Michel Bouchet, as I was looking at your site I noticed the following.
Here: http://www.bigprimes.net/archive/fermat/

I can read this on the last line:
2+1 --- 1st Prime. (2 to the power 1 plus 1). In other words 3 --- 1st Prime.
But 3 is the 2nd prime.
The line just above seems to show the same kind of issue.
The other lines (starting from the 7th prime) seems to OK.

If what I write above is not correct, I may be missreading the information displayed on the page.

All the best.

Michel

**Comment by craigmayhew** [comment]
Thanks Michel! Fixed.

**Comment by zaxonus** [comment]
You are welcome.

**Comment by zaxonus** [comment]
I am myself interested in prime numbers and last week I published to apps on the appStore [Primal](https://sifkif.wixsite.com/primal) and [Primal+](https://sifkif.wixsite.com/primal-plus).
