### ISSUE TITLE
Erroneous "cruncher" report.

### ISSUE THREAD

**Issue by ruminations** [craigmayhew/bigprimes.net#8]
Your web page:

http://www.bigprimes.net/cruncher/

when queried with:

39850859372740856242099725857146778412298219829168807875828109446556425650123663580223371858956633234197793823836800702258795237043648054470513616206175403378621362265360297207018853335998176098526621

tells me it is not prime.  In truth, it is simply too large for your algorithms.  It is prime, as are a number of other large values I tried, which yield the same erroneous assertion.

**Comment by craigmayhew** [comment]
Thanks for reporting the issue. The code was failing to switch to a probabilistic test when the number was larger than the 1.4 billionth database record. This site should now be correct.
